name: Unit Testing
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn test
      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./packages/server/coverage/lcov.info
          flags: server
          name: Stream Server
